In [ ]:
!pip install pandas

^C

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\parul\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in e:\parul\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.9 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.8 MB 1.9 MB/s eta 0:00:05
   ----- ---------------------------------- 1.3/9.8 MB 2.0 MB/s eta 0:00:05
   ------- -------------------------------- 1.8/9.8 MB 2.0 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.8 MB 2.0 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.8 MB 2.0 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.8 MB 2.0 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.8 MB 2.0 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.8 MB 2.0 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.8 MB 1.9 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.8 MB 1.9 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.8 MB 1.9 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.8 MB 1.9 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 1.9 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.8 MB 1.9 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.8 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.8 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.8 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 1.7 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 1.7 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.8 MB 1.7 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.8 MB 1.7 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.7 MB/s eta 0:00:00
Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 1.7 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.5 MB 1.5 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/12.5 MB 1.4 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/12.5 MB 1.5 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/12.5 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.5 MB 1.4 MB/s eta 0:00:08
   ------- -------------------------------- 2.4/12.5 MB 1.4 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.5 MB 1.4 MB/s eta 0:00:08
   --------- ------------------------------ 2.9/12.5 MB 1.4 MB/s eta 0:00:07
   ---------- ----------------------------- 3.1/12.5 MB 1.4 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/12.5 MB 1.4 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.5 MB 1.4 MB/s eta 0:00:07
   ------------- -------------------------- 4.2/12.5 MB 1.4 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.5 MB 1.4 MB/s eta 0:00:06
   -------------- ------------------------- 4.5/12.5 MB 1.4 MB/s eta 0:00:06
   --------------- ------------------------ 4.7/12.5 MB 1.4 MB/s eta 0:00:06
   --------------- ------------------------ 5.0/12.5 MB 1.4 MB/s eta 0:00:06
   --------------- ------------------------ 5.0/12.5 MB 1.4 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.5 MB 1.3 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.5 MB 1.3 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/12.5 MB 1.3 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.5 MB 1.2 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.5 MB 1.2 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.5 MB 1.2 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.5 MB 1.2 MB/s eta 0:00:06
   ----------------- ---------------------- 5.5/12.5 MB 1.2 MB/s eta 0:00:06
   ------------------ --------------------- 5.8/12.5 MB 1.0 MB/s eta 0:00:07
   ------------------ --------------------- 5.8/12.5 MB 1.0 MB/s eta 0:00:07
   ------------------- -------------------- 6.0/12.5 MB 963.8 kB/s eta 0:00:07
   ------------------- -------------------- 6.0/12.5 MB 963.8 kB/s eta 0:00:07
   ------------------- -------------------- 6.0/12.5 MB 963.8 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.5 MB 914.4 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.5 MB 914.4 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.5 MB 914.4 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.5 MB 914.4 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.5 MB 914.4 kB/s eta 0:00:07
   -------------------- ------------------- 6.3/12.5 MB 914.4 kB/s eta 0:00:07
   --------------------- ------------------ 6.6/12.5 MB 821.8 kB/s eta 0:00:08
   --------------------- ------------------ 6.6/12.5 MB 821.8 kB/s eta 0:00:08
   --------------------- ------------------ 6.6/12.5 MB 821.8 kB/s eta 0:00:08
   --------------------- ------------------ 6.8/12.5 MB 791.4 kB/s eta 0:00:08
   --------------------- ------------------ 6.8/12.5 MB 791.4 kB/s eta 0:00:08
   ---------------------- ----------------- 7.1/12.5 MB 783.1 kB/s eta 0:00:07
   ---------------------- ----------------- 7.1/12.5 MB 783.1 kB/s eta 0:00:07
   ----------------------- ---------------- 7.3/12.5 MB 777.0 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.5 MB 775.2 kB/s eta 0:00:07
   ------------------------ --------------- 7.6/12.5 MB 775.2 kB/s eta 0:00:07
   ------------------------- -------------- 7.9/12.5 MB 773.5 kB/s eta 0:00:06
   ------------------------- -------------- 7.9/12.5 MB 773.5 kB/s eta 0:00:06
   -------------------------- ------------- 8.1/12.5 MB 773.1 kB/s eta 0:00:06
   -------------------------- ------------- 8.1/12.5 MB 773.1 kB/s eta 0:00:06
   -------------------------- ------------- 8.1/12.5 MB 773.1 kB/s eta 0:00:06
   -------------------------- ------------- 8.4/12.5 MB 752.7 kB/s eta 0:00:06
   -------------------------- ------------- 8.4/12.5 MB 752.7 kB/s eta 0:00:06
   -------------------------- ------------- 8.4/12.5 MB 752.7 kB/s eta 0:00:06
   --------------------------- ------------ 8.7/12.5 MB 727.5 kB/s eta 0:00:06
   --------------------------- ------------ 8.7/12.5 MB 727.5 kB/s eta 0:00:06
   --------------------------- ------------ 8.7/12.5 MB 727.5 kB/s eta 0:00:06
   ---------------------------- ----------- 8.9/12.5 MB 710.7 kB/s eta 0:00:05
   ---------------------------- ----------- 8.9/12.5 MB 710.7 kB/s eta 0:00:05
   ---------------------------- ----------- 8.9/12.5 MB 710.7 kB/s eta 0:00:05
   ---------------------------- ----------- 8.9/12.5 MB 710.7 kB/s eta 0:00:05
   ---------------------------- ----------- 8.9/12.5 MB 710.7 kB/s eta 0:00:05
   ---------------------------- ----------- 8.9/12.5 MB 710.7 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.5 MB 673.5 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.5 MB 673.5 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.5 MB 673.5 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.5 MB 673.5 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.5 MB 673.5 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.5 MB 673.5 kB/s eta 0:00:05
   ----------------------------- ---------- 9.2/12.5 MB 673.5 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.5 MB 625.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.5 MB 625.3 kB/s eta 0:00:05
   ------------------------------ --------- 9.4/12.5 MB 625.3 kB/s eta 0:00:05
   ------------------------------- -------- 9.7/12.5 MB 610.7 kB/s eta 0:00:05
   ------------------------------- -------- 9.7/12.5 MB 610.7 kB/s eta 0:00:05
   ------------------------------- -------- 9.7/12.5 MB 610.7 kB/s eta 0:00:05
   ------------------------------- -------- 10.0/12.5 MB 610.4 kB/s eta 0:00:05
   -------------------------------- ------- 10.2/12.5 MB 613.6 kB/s eta 0:00:04
   -------------------------------- ------- 10.2/12.5 MB 613.6 kB/s eta 0:00:04
   --------------------------------- ------ 10.5/12.5 MB 618.5 kB/s eta 0:00:04
   ---------------------------------- ----- 10.7/12.5 MB 623.1 kB/s eta 0:00:03
   ----------------------------------- ---- 11.0/12.5 MB 628.8 kB/s eta 0:00:03
   ------------------------------------ --- 11.3/12.5 MB 635.4 kB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.5 MB 635.4 kB/s eta 0:00:02
   ------------------------------------- -- 11.5/12.5 MB 641.9 kB/s eta 0:00:02
   -------------------------------------- - 12.1/12.5 MB 657.1 kB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 664.7 kB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 668.6 kB/s eta 0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.2 pandas-3.0.5 tzdata-2026.3

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/pandas/

In [ ]:
# import pandas as pd

### Series
- A panda series is a 1D array-like object that can hold any data type.
- It is similar to column in a table.

In [3]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series: \n",series)

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
## create a Series from dictionary
data1 = {'a':1,'b':2}
series_dict = pd.Series(data1)
print(series_dict)

a    1
b    2
dtype: int64

In [5]:
data2 = {1:"10",2:2.2,3:30,4:"bharath"}
series_data2 = pd.Series(data2)
print(series_data2)

1         10
2        2.2
3         30
4    bharath
dtype: object

In [6]:
data = [16,26,36]
indexes = ['a','b','c']
pd.Series(data,index=indexes)

a    16
b    26
c    36
dtype: int64

### DataFrame
- 2 Dimensional
- multiple rows and columns

In [7]:
## DataFrame from the dictionary

data = {
    'studentName' : ['bharath','Surya','Sita'],
    'Age' : [18,17,18],
    'City' : ['Vadodara','narsipatnam','Srikakulam']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

  studentName  Age         City
0     bharath   18     Vadodara
1       Surya   17  narsipatnam
2        Sita   18   Srikakulam
<class 'pandas.DataFrame'>

In [8]:
Animal = {
    'AnimalName':['Dog','Cat','BUffalo','Cow'],
    'Expansion' : [10,7,15,25],
}

df1 = pd.DataFrame(Animal)
print(df1)
df1.size

  AnimalName  Expansion
0        Dog         10
1        Cat          7
2    BUffalo         15
3        Cow         25

8

In [9]:
import numpy as np
np1 = np.array(df)
print(np1)
np1.size

[['bharath' 18 'Vadodara']
 ['Surya' 17 'narsipatnam']
 ['Sita' 18 'Srikakulam']]

9

In [10]:
## Creating Dtaframe by list of Dictionaries

data = [
    {'name':'BHarath','Age':18,'City':'Vadodara'},
    {'name':'BHarath','Age':18,'City':'Vadodara'},
    {'name':'BHarath','Age':18,'City':'Vadodara'},
    {'name':'BHarath','Age':18,'City':'Vadodara'},
]
print(pd.DataFrame(data))

      name  Age      City
0  BHarath   18  Vadodara
1  BHarath   18  Vadodara
2  BHarath   18  Vadodara
3  BHarath   18  Vadodara

In [11]:
df3 = pd.read_csv('sales_data.csv')
df3.head(5)
df3.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [12]:
## Accessing data from dataframe

df

  studentName  Age         City
0     bharath   18     Vadodara
1       Surya   17  narsipatnam
2        Sita   18   Srikakulam

In [13]:
df['City']

0       Vadodara
1    narsipatnam
2     Srikakulam
Name: City, dtype: str

- loc: to go with the column

In [14]:
df.loc[0]

studentName     bharath
Age                  18
City           Vadodara
Name: 0, dtype: object

In [15]:
df.iloc[0][1]

KeyError: 1

In [16]:
df

  studentName  Age         City
0     bharath   18     Vadodara
1       Surya   17  narsipatnam
2        Sita   18   Srikakulam

- Accessing a Specified Element with index of column

In [17]:
df.at[2,'Age']

np.int64(18)

In [18]:
df.at[0,'studentName']

'bharath'

- Accessing by iat by both row and column index

In [19]:
df.iat[2,2]
df.iat[1,2]

'narsipatnam'

In [20]:
df

  studentName  Age         City
0     bharath   18     Vadodara
1       Surya   17  narsipatnam
2        Sita   18   Srikakulam

In [21]:
## Adding a column into the dataFrame

df['groups'] = ['CSE','BSC','EEE']

In [22]:
df

  studentName  Age         City groups
0     bharath   18     Vadodara    CSE
1       Surya   17  narsipatnam    BSC
2        Sita   18   Srikakulam    EEE

In [23]:
df.drop('groups',axis=1)

  studentName  Age         City
0     bharath   18     Vadodara
1       Surya   17  narsipatnam
2        Sita   18   Srikakulam

In [24]:
df

  studentName  Age         City groups
0     bharath   18     Vadodara    CSE
1       Surya   17  narsipatnam    BSC
2        Sita   18   Srikakulam    EEE

In [25]:
df.drop('groups',axis=1,inplace=True)

In [26]:
df

  studentName  Age         City
0     bharath   18     Vadodara
1       Surya   17  narsipatnam
2        Sita   18   Srikakulam

In [27]:
df3

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [28]:
df3.drop('Region',axis=1,inplace=True)

In [29]:
df3

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,PayPal
...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Credit Card

In [30]:
df3['Transaction ID'] = df3['Transaction ID']+10

In [31]:
df3

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
0,10011,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,Credit Card
1,10012,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,PayPal
2,10013,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Debit Card
3,10014,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,Credit Card
4,10015,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,PayPal
...,...,...,...,...,...,...,...,...
235,10246,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,PayPal
236,10247,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Debit Card
237,10248,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,Credit Card
238,10249,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,PayPal
239,10250,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Credit Card

In [32]:
df3.drop(0)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
1,10012,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,PayPal
2,10013,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Debit Card
3,10014,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,Credit Card
4,10015,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,PayPal
5,10016,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Credit Card
...,...,...,...,...,...,...,...,...
235,10246,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,PayPal
236,10247,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Debit Card
237,10248,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,Credit Card
238,10249,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,PayPal
239,10250,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Credit Card

In [33]:
df3.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10130.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10011.00000    1.000000     6.500000       6.500000
25%       10070.75000    1.000000    29.500000      62.965000
50%       10130.50000    2.000000    89.990000     179.970000
75%       10190.25000    3.000000   249.990000     399.225000
max       10250.00000   10.000000  3899.990000    3899.990000